server {
    listen 80;
    root /var/www/html/public;
    index index.php;

    types_hash_max_size 4096;
    types_hash_bucket_size 256;
    client_max_body_size 900M;
    client_body_buffer_size 128k;
    client_header_buffer_size 1k;
    large_client_header_buffers 4 32k;
    gzip on;
    gzip_comp_level 5;
    gzip_types text/plain text/css application/json application/javascript \
               text/xml application/xml application/xml+rss text/javascript \
               application/x-javascript image/svg+xml;
    location /health {
        return 200;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass 127.0.0.1:9000;
        # fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    }
    location ~ /\.env {
        deny all;
    }
}
